# Notebooks.
notebooks-source: prod
notebooks-target: notebooks
master-target: master
demos-target: demos

# Other content.
references-source: references
references-target: references
scripts-source: scripts
images-source: images
images-target: images

# AWS S3 storage.
s3-bucket: geocomp
s3-path: data

# What --all means.
all:
  - geocomp
  - eda
  - model-zoo
  - geo-ml
  - peteng-ml
  - geocomp-dl
