name: test-builds
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  test-builds:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: test all builds
        run: |
          python ./geocomputing.py test --all --environment
      - name: test environment
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: geocomp-all
          environment-file: environment-all.yml
