name: test-builds
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  test-builds:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install geocomputing development dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Test all courses build
        run: |
          python ./geocomputing.py test --all --environment
      - name: Test conda environment
        uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: environment-all.yml
