name: test-builds
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  test-builds:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            command: C:\Miniconda\condabin\conda env create -f environment.yml
          - os: ubuntu-latest
            command: conda env create -f environment-all.yml
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install geocomputing development dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Test all courses build
        run: |
          python ./geocomputing.py test --environment --all
      - name: Test conda environment
        run: |
          ${{ matrix.command }}
